<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MSI" ignored="0" name="Command line test" tests="5" failures="1" timestamp="26 十月 2018 05:38:17 GMT" time="2.828" errors="0">
  <testcase name="@AfterMethod springTestContextAfterTestMethod" time="0.0" classname="org.springframework.test.context.testng.AbstractTestNGSpringContextTests">
    <failure type="org.springframework.transaction.UnexpectedRollbackException" message="Transaction silently rolled back because it has been marked as rollback-only">
      <![CDATA[org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only
at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:755)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
at org.springframework.test.context.transaction.TransactionContext.endTransaction(TransactionContext.java:131)
at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:216)
at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:443)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextAfterTestMethod(AbstractTestNGSpringContextTests.java:210)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod springTestContextAfterTestMethod -->
  <testcase name="addUserFail" time="0.147" classname="springrest.api.controller.UserControllerTest"/>
  <testcase name="addUserPass" time="0.14" classname="springrest.api.controller.UserControllerTest">
    <failure type="java.lang.AssertionError" message="Range for response status value 500 expected:&amp;lt;SUCCESSFUL&amp;gt; but was:&amp;lt;SERVER_ERROR&amp;gt;">
      <![CDATA[java.lang.AssertionError: Range for response status value 500 expected:<SUCCESSFUL> but was:<SERVER_ERROR>
at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:55)
at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:82)
at org.springframework.test.web.servlet.result.StatusResultMatchers.lambda$is2xxSuccessful$3(StatusResultMatchers.java:78)
at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:178)
at springrest.api.controller.UserControllerTest.addUserPass(UserControllerTest.java:73)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- addUserPass -->
  <testcase name="getUser" time="0.0" classname="springrest.api.controller.UserControllerTest">
    <skipped/>
  </testcase> <!-- getUser -->
  <testcase name="getUsers" time="0.0" classname="springrest.api.controller.UserControllerTest">
    <skipped/>
  </testcase> <!-- getUsers -->
  <testcase name="getUsers2" time="0.0" classname="springrest.api.controller.UserControllerTest">
    <skipped/>
  </testcase> <!-- getUsers2 -->
</testsuite> <!-- Command line test -->
